openapi: 3.1.0
info:
  title: Octo Deck API
  version: 1.0.0
tags: []
paths:
  /cards:
    get:
      operationId: getCards
      summary: カード一覧取得
      description: Octo Deck API
      parameters: []
      responses:
        "200":
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  cards:
                    type: array
                    items:
                      $ref: "#/components/schemas/Card"
                required:
                  - cards
  /cards/me:
    get:
      operationId: getMyCard
      summary: 自分のカード取得
      parameters: []
      responses:
        "200":
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  card:
                    $ref: "#/components/schemas/Card"
                required:
                  - card
  /cards/{id}:
    get:
      operationId: getCard
      summary: カード取得
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  card:
                    $ref: "#/components/schemas/Card"
                required:
                  - card
components:
  schemas:
    Card:
      type: object
      required:
        - id
        - userName
        - fullName
        - iconUrl
      properties:
        id:
          type: string
        userName:
          type: string
        fullName:
          type: string
        iconUrl:
          type: string
servers:
  - url: http://localhost:8080
    description: Local
    variables: {}
  - url: https://dev.api.octo-deck.furari.co
    description: Development
    variables: {}
  - url: https://stg.api.octo-deck.furari.co
    description: Staging
    variables: {}
  - url: https://api.octo-deck.furari.co
    description: Production
    variables: {}
